version: "3.4"
services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: symfony_php
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - .:/srv/app:rw,cached
    links:
      - redis
    environment:
      APP_ENV: dev
  nginx:
    image: nginx:1.19.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/scorecalc.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/srv/app:ro
    depends_on:
      - php
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data/redis:/data/redis
