version: "3.4"
services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: symfony_php
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - ./:/srv/app/
      - ./.docker/data/db:/etc/app/db
    environment:
      APP_ENV: dev
  nginx:
    image: nginx:1.19.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/scorecalc.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/srv/app
    depends_on:
      - php
